import turtle
littleguy = turtle.Turtle()
littleguy.shape("turtle")
littleguy.pu()
littleguy.rt(90)
littleguy.fd(200)
littleguy.lt(90)
littleguy.pd()
littleguy.fillcolor("red")
littleguy.begin_fill()
littleguy.circle(200)
littleguy.end_fill()
littleguy.pu()
littleguy.lt(90)
littleguy.fd(100)
littleguy.rt(90)
littleguy.pd()
littleguy.fillcolor("yellow")
littleguy.begin_fill()
littleguy.circle(100)
littleguy.end_fill()
littleguy.pu()
littleguy.lt(90)
littleguy.fd(90)
littleguy.pd()
littleguy.write("Nil Sine Labore", False, "center", tuple[12])
littleguy.ht()
turtle.done()
